[package]
name = "lua-format"
version = "0.1.0"
authors = ["Alexey Minchakov <lexaaim@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.19.0"

[dependencies]
lalrpop-util = "0.19.0"
regex = "1"
phf = { version = "0.8", features = ["macros"] }
